#define ESP_WIFI_SSID      "YOUR_SSID"
#define ESP_WIFI_PASS      "YOUR_PASSWORD"
#define ESP_MAXIMUM_RETRY  5

#define ESP_WIFI_SAE_MODE  "BOTH"
#define EXAMPLE_H2E_IDENTIFIER ""
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD "WPA2 PSK"